param(
  [Parameter(Mandatory = $true)]
  [string]$RepoPath,
  [string]$InstallRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path,
  [string]$ConfigPath = (Join-Path $env:LOCALAPPDATA 'RedactWall\endpoint-agent.env'),
  [string[]]$AllowedHost = @(),
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Assert-SafeHost {
  param([string]$HostName)
  if ([string]::IsNullOrWhiteSpace($HostName) -or $HostName -notmatch '^[A-Za-z0-9.-]{1,253}$' -or $HostName.Contains('..')) {
    throw "Invalid allowed host: $HostName"
  }
}

function Convert-ToShellSingleQuotedPath {
  param([string]$Value)
  $normalized = $Value.Replace('\', '/')
  return "'" + $normalized.Replace("'", "'\''") + "'"
}

function Resolve-GitDir {
  param([string]$Repo)
  $gitDir = (& git -C $Repo rev-parse --git-dir 2>$null)
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitDir)) {
    throw "RepoPath is not a git repository"
  }
  $gitDir = $gitDir.Trim()
  if ([System.IO.Path]::IsPathRooted($gitDir)) {
    return (Resolve-Path -LiteralPath $gitDir).Path
  }
  return (Resolve-Path -LiteralPath (Join-Path $Repo $gitDir)).Path
}

$repo = (Resolve-Path -LiteralPath $RepoPath).Path
$root = (Resolve-Path -LiteralPath $InstallRoot).Path
$collector = Join-Path $root 'sensors\endpoint-agent\collectors\git-push-guard.js'
if (-not (Test-Path -LiteralPath $collector -PathType Leaf)) {
  throw "RedactWall git push guard collector was not found"
}

$gitDir = Resolve-GitDir -Repo $repo
$hooksDir = Join-Path $gitDir 'hooks'
New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null
$hookPath = Join-Path $hooksDir 'pre-push'
$marker = 'RedactWall Git Push Guard'

if ((Test-Path -LiteralPath $hookPath -PathType Leaf) -and -not $Force) {
  $existing = Get-Content -LiteralPath $hookPath -Raw
  if ($existing -notmatch [regex]::Escape($marker)) {
    throw "A pre-push hook already exists. Re-run with -Force after reviewing it."
  }
}

$allowedArgs = @()
foreach ($hostName in $AllowedHost) {
  Assert-SafeHost -HostName $hostName
  $allowedArgs += "  --allowed-host '$hostName'"
}

$collectorPath = Convert-ToShellSingleQuotedPath -Value $collector
$configPath = Convert-ToShellSingleQuotedPath -Value $ConfigPath
$remoteUrlLine = '  --remote-url "$2"'
if ($allowedArgs.Count) {
  $remoteUrlLine += ' \'
}
$allowedText = if ($allowedArgs.Count) { "`n" + ($allowedArgs -join " \`n") } else { '' }

$hook = @"
#!/bin/sh
# $marker - generated by scripts/install-git-push-guard.ps1
export REDACTWALL_ENV_PATH=$configPath
node $collectorPath \
  --pre-push \
  --repo "`$(git rev-parse --show-toplevel)" \
  --remote-name "`$1" \
$remoteUrlLine$allowedText
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($hookPath, ($hook.TrimEnd() + "`n"), $utf8NoBom)
Write-Host "Installed RedactWall git push guard hook at $hookPath"
